/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ngspice_sim.proto */

#ifndef PROTOBUF_C_ngspice_5fsim_2eproto__INCLUDED
#define PROTOBUF_C_ngspice_5fsim_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Ngspice__SimRequest Ngspice__SimRequest;
typedef struct Ngspice__SimRequest__OptionsEntry Ngspice__SimRequest__OptionsEntry;
typedef struct Ngspice__BatchSimRequest Ngspice__BatchSimRequest;
typedef struct Ngspice__VectorData Ngspice__VectorData;
typedef struct Ngspice__SimResult Ngspice__SimResult;
typedef struct Ngspice__SimResult__NodeVoltagesEntry Ngspice__SimResult__NodeVoltagesEntry;
typedef struct Ngspice__SimResult__BranchCurrentsEntry Ngspice__SimResult__BranchCurrentsEntry;
typedef struct Ngspice__BatchSimResult Ngspice__BatchSimResult;
typedef struct Ngspice__ServerStats Ngspice__ServerStats;
typedef struct Ngspice__NRIteration Ngspice__NRIteration;
typedef struct Ngspice__LimiterActivation Ngspice__LimiterActivation;
typedef struct Ngspice__GminStep Ngspice__GminStep;
typedef struct Ngspice__SourceStep Ngspice__SourceStep;
typedef struct Ngspice__DeviceLoadValuesEntry Ngspice__DeviceLoadValuesEntry;
typedef struct Ngspice__DeviceLoad Ngspice__DeviceLoad;
typedef struct Ngspice__MatrixCondition Ngspice__MatrixCondition;
typedef struct Ngspice__DiagEvent Ngspice__DiagEvent;


/* --- enums --- */

typedef enum _Ngspice__SimResult__ErrorCode {
  NGSPICE__SIM_RESULT__ERROR_CODE__OK = 0,
  NGSPICE__SIM_RESULT__ERROR_CODE__PARSE_ERROR = 1,
  NGSPICE__SIM_RESULT__ERROR_CODE__CONVERGENCE_FAILURE = 2,
  NGSPICE__SIM_RESULT__ERROR_CODE__SINGULAR_MATRIX = 3,
  NGSPICE__SIM_RESULT__ERROR_CODE__INTERNAL_ERROR = 4,
  NGSPICE__SIM_RESULT__ERROR_CODE__TIMEOUT = 5,
  /*
   * Admission control: all workers busy and wait queue is full.
   */
  NGSPICE__SIM_RESULT__ERROR_CODE__SERVER_BUSY = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NGSPICE__SIM_RESULT__ERROR_CODE)
} Ngspice__SimResult__ErrorCode;

/* --- messages --- */

struct  Ngspice__SimRequest__OptionsEntry
{
  ProtobufCMessage base;
  char *key;
  double value;
};
#define NGSPICE__SIM_REQUEST__OPTIONS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ngspice__sim_request__options_entry__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  Ngspice__SimRequest
{
  ProtobufCMessage base;
  char *netlist;
  char *analysis;
  size_t n_options;
  Ngspice__SimRequest__OptionsEntry **options;
  protobuf_c_boolean stream_diagnostics;
  char *request_id;
};
#define NGSPICE__SIM_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ngspice__sim_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, 0, (char *)protobuf_c_empty_string }


struct  Ngspice__BatchSimRequest
{
  ProtobufCMessage base;
  size_t n_requests;
  Ngspice__SimRequest **requests;
};
#define NGSPICE__BATCH_SIM_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ngspice__batch_sim_request__descriptor) \
    , 0,NULL }


struct  Ngspice__VectorData
{
  ProtobufCMessage base;
  char *name;
  size_t n_real_values;
  double *real_values;
  size_t n_imag_values;
  double *imag_values;
};
#define NGSPICE__VECTOR_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ngspice__vector_data__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL, 0,NULL }


struct  Ngspice__SimResult__NodeVoltagesEntry
{
  ProtobufCMessage base;
  char *key;
  double value;
};
#define NGSPICE__SIM_RESULT__NODE_VOLTAGES_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ngspice__sim_result__node_voltages_entry__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  Ngspice__SimResult__BranchCurrentsEntry
{
  ProtobufCMessage base;
  char *key;
  double value;
};
#define NGSPICE__SIM_RESULT__BRANCH_CURRENTS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ngspice__sim_result__branch_currents_entry__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  Ngspice__SimResult
{
  ProtobufCMessage base;
  char *request_id;
  protobuf_c_boolean converged;
  int32_t iterations;
  size_t n_node_voltages;
  Ngspice__SimResult__NodeVoltagesEntry **node_voltages;
  size_t n_branch_currents;
  Ngspice__SimResult__BranchCurrentsEntry **branch_currents;
  size_t n_warnings;
  char **warnings;
  double wall_time_ms;
  Ngspice__SimResult__ErrorCode error;
  size_t n_vectors;
  Ngspice__VectorData **vectors;
  char *analysis_type;
  int32_t num_points;
};
#define NGSPICE__SIM_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ngspice__sim_result__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, 0,NULL, 0,NULL, 0,NULL, 0, NGSPICE__SIM_RESULT__ERROR_CODE__OK, 0,NULL, (char *)protobuf_c_empty_string, 0 }


struct  Ngspice__BatchSimResult
{
  ProtobufCMessage base;
  size_t n_results;
  Ngspice__SimResult **results;
  double total_wall_time_ms;
};
#define NGSPICE__BATCH_SIM_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ngspice__batch_sim_result__descriptor) \
    , 0,NULL, 0 }


struct  Ngspice__ServerStats
{
  ProtobufCMessage base;
  int32_t pool_size;
  uint32_t admit_queued;
  uint32_t admit_cap;
  int32_t workers_busy;
  uint64_t requests_completed;
  uint64_t server_busy_replies;
  uint64_t worker_restarts;
  uint64_t request_timeouts;
};
#define NGSPICE__SERVER_STATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ngspice__server_stats__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0 }


struct  Ngspice__NRIteration
{
  ProtobufCMessage base;
  int32_t iter;
  double max_dx;
  int32_t noncon;
  protobuf_c_boolean converged;
  double max_rhs;
  double damp;
};
#define NGSPICE__NRITERATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ngspice__nriteration__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


struct  Ngspice__LimiterActivation
{
  ProtobufCMessage base;
  char *function;
  char *instance;
  double vnew_raw;
  double vnew_limited;
  double vold;
  double vcrit;
  double vto;
};
#define NGSPICE__LIMITER_ACTIVATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ngspice__limiter_activation__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0 }


struct  Ngspice__GminStep
{
  ProtobufCMessage base;
  double value;
  protobuf_c_boolean converged;
  int32_t iterations;
};
#define NGSPICE__GMIN_STEP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ngspice__gmin_step__descriptor) \
    , 0, 0, 0 }


struct  Ngspice__SourceStep
{
  ProtobufCMessage base;
  double factor;
  protobuf_c_boolean converged;
  int32_t iterations;
};
#define NGSPICE__SOURCE_STEP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ngspice__source_step__descriptor) \
    , 0, 0, 0 }


struct  Ngspice__DeviceLoadValuesEntry
{
  ProtobufCMessage base;
  char *key;
  double value;
};
#define NGSPICE__DEVICE_LOAD_VALUES_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ngspice__device_load_values_entry__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  Ngspice__DeviceLoad
{
  ProtobufCMessage base;
  char *type;
  char *instance;
  size_t n_values;
  Ngspice__DeviceLoadValuesEntry **values;
};
#define NGSPICE__DEVICE_LOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ngspice__device_load__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL }


struct  Ngspice__MatrixCondition
{
  ProtobufCMessage base;
  int32_t size;
  double min_pivot;
  double max_pivot;
  double condition_ratio;
};
#define NGSPICE__MATRIX_CONDITION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ngspice__matrix_condition__descriptor) \
    , 0, 0, 0, 0 }


typedef enum {
  NGSPICE__DIAG_EVENT__EVENT__NOT_SET = 0,
  NGSPICE__DIAG_EVENT__EVENT_NR_ITER = 10,
  NGSPICE__DIAG_EVENT__EVENT_LIMITER = 11,
  NGSPICE__DIAG_EVENT__EVENT_GMIN = 12,
  NGSPICE__DIAG_EVENT__EVENT_SRC_STEP = 13,
  NGSPICE__DIAG_EVENT__EVENT_DEVICE = 14,
  NGSPICE__DIAG_EVENT__EVENT_MATRIX = 15
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NGSPICE__DIAG_EVENT__EVENT__CASE)
} Ngspice__DiagEvent__EventCase;

struct  Ngspice__DiagEvent
{
  ProtobufCMessage base;
  char *request_id;
  int64_t timestamp_us;
  Ngspice__DiagEvent__EventCase event_case;
  union {
    Ngspice__NRIteration *nr_iter;
    Ngspice__LimiterActivation *limiter;
    Ngspice__GminStep *gmin;
    Ngspice__SourceStep *src_step;
    Ngspice__DeviceLoad *device;
    Ngspice__MatrixCondition *matrix;
  };
};
#define NGSPICE__DIAG_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ngspice__diag_event__descriptor) \
    , (char *)protobuf_c_empty_string, 0, NGSPICE__DIAG_EVENT__EVENT__NOT_SET, {0} }


/* Ngspice__SimRequest__OptionsEntry methods */
void   ngspice__sim_request__options_entry__init
                     (Ngspice__SimRequest__OptionsEntry         *message);
/* Ngspice__SimRequest methods */
void   ngspice__sim_request__init
                     (Ngspice__SimRequest         *message);
size_t ngspice__sim_request__get_packed_size
                     (const Ngspice__SimRequest   *message);
size_t ngspice__sim_request__pack
                     (const Ngspice__SimRequest   *message,
                      uint8_t             *out);
size_t ngspice__sim_request__pack_to_buffer
                     (const Ngspice__SimRequest   *message,
                      ProtobufCBuffer     *buffer);
Ngspice__SimRequest *
       ngspice__sim_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ngspice__sim_request__free_unpacked
                     (Ngspice__SimRequest *message,
                      ProtobufCAllocator *allocator);
/* Ngspice__BatchSimRequest methods */
void   ngspice__batch_sim_request__init
                     (Ngspice__BatchSimRequest         *message);
size_t ngspice__batch_sim_request__get_packed_size
                     (const Ngspice__BatchSimRequest   *message);
size_t ngspice__batch_sim_request__pack
                     (const Ngspice__BatchSimRequest   *message,
                      uint8_t             *out);
size_t ngspice__batch_sim_request__pack_to_buffer
                     (const Ngspice__BatchSimRequest   *message,
                      ProtobufCBuffer     *buffer);
Ngspice__BatchSimRequest *
       ngspice__batch_sim_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ngspice__batch_sim_request__free_unpacked
                     (Ngspice__BatchSimRequest *message,
                      ProtobufCAllocator *allocator);
/* Ngspice__VectorData methods */
void   ngspice__vector_data__init
                     (Ngspice__VectorData         *message);
size_t ngspice__vector_data__get_packed_size
                     (const Ngspice__VectorData   *message);
size_t ngspice__vector_data__pack
                     (const Ngspice__VectorData   *message,
                      uint8_t             *out);
size_t ngspice__vector_data__pack_to_buffer
                     (const Ngspice__VectorData   *message,
                      ProtobufCBuffer     *buffer);
Ngspice__VectorData *
       ngspice__vector_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ngspice__vector_data__free_unpacked
                     (Ngspice__VectorData *message,
                      ProtobufCAllocator *allocator);
/* Ngspice__SimResult__NodeVoltagesEntry methods */
void   ngspice__sim_result__node_voltages_entry__init
                     (Ngspice__SimResult__NodeVoltagesEntry         *message);
/* Ngspice__SimResult__BranchCurrentsEntry methods */
void   ngspice__sim_result__branch_currents_entry__init
                     (Ngspice__SimResult__BranchCurrentsEntry         *message);
/* Ngspice__SimResult methods */
void   ngspice__sim_result__init
                     (Ngspice__SimResult         *message);
size_t ngspice__sim_result__get_packed_size
                     (const Ngspice__SimResult   *message);
size_t ngspice__sim_result__pack
                     (const Ngspice__SimResult   *message,
                      uint8_t             *out);
size_t ngspice__sim_result__pack_to_buffer
                     (const Ngspice__SimResult   *message,
                      ProtobufCBuffer     *buffer);
Ngspice__SimResult *
       ngspice__sim_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ngspice__sim_result__free_unpacked
                     (Ngspice__SimResult *message,
                      ProtobufCAllocator *allocator);
/* Ngspice__BatchSimResult methods */
void   ngspice__batch_sim_result__init
                     (Ngspice__BatchSimResult         *message);
size_t ngspice__batch_sim_result__get_packed_size
                     (const Ngspice__BatchSimResult   *message);
size_t ngspice__batch_sim_result__pack
                     (const Ngspice__BatchSimResult   *message,
                      uint8_t             *out);
size_t ngspice__batch_sim_result__pack_to_buffer
                     (const Ngspice__BatchSimResult   *message,
                      ProtobufCBuffer     *buffer);
Ngspice__BatchSimResult *
       ngspice__batch_sim_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ngspice__batch_sim_result__free_unpacked
                     (Ngspice__BatchSimResult *message,
                      ProtobufCAllocator *allocator);
/* Ngspice__ServerStats methods */
void   ngspice__server_stats__init
                     (Ngspice__ServerStats         *message);
size_t ngspice__server_stats__get_packed_size
                     (const Ngspice__ServerStats   *message);
size_t ngspice__server_stats__pack
                     (const Ngspice__ServerStats   *message,
                      uint8_t             *out);
size_t ngspice__server_stats__pack_to_buffer
                     (const Ngspice__ServerStats   *message,
                      ProtobufCBuffer     *buffer);
Ngspice__ServerStats *
       ngspice__server_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ngspice__server_stats__free_unpacked
                     (Ngspice__ServerStats *message,
                      ProtobufCAllocator *allocator);
/* Ngspice__NRIteration methods */
void   ngspice__nriteration__init
                     (Ngspice__NRIteration         *message);
size_t ngspice__nriteration__get_packed_size
                     (const Ngspice__NRIteration   *message);
size_t ngspice__nriteration__pack
                     (const Ngspice__NRIteration   *message,
                      uint8_t             *out);
size_t ngspice__nriteration__pack_to_buffer
                     (const Ngspice__NRIteration   *message,
                      ProtobufCBuffer     *buffer);
Ngspice__NRIteration *
       ngspice__nriteration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ngspice__nriteration__free_unpacked
                     (Ngspice__NRIteration *message,
                      ProtobufCAllocator *allocator);
/* Ngspice__LimiterActivation methods */
void   ngspice__limiter_activation__init
                     (Ngspice__LimiterActivation         *message);
size_t ngspice__limiter_activation__get_packed_size
                     (const Ngspice__LimiterActivation   *message);
size_t ngspice__limiter_activation__pack
                     (const Ngspice__LimiterActivation   *message,
                      uint8_t             *out);
size_t ngspice__limiter_activation__pack_to_buffer
                     (const Ngspice__LimiterActivation   *message,
                      ProtobufCBuffer     *buffer);
Ngspice__LimiterActivation *
       ngspice__limiter_activation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ngspice__limiter_activation__free_unpacked
                     (Ngspice__LimiterActivation *message,
                      ProtobufCAllocator *allocator);
/* Ngspice__GminStep methods */
void   ngspice__gmin_step__init
                     (Ngspice__GminStep         *message);
size_t ngspice__gmin_step__get_packed_size
                     (const Ngspice__GminStep   *message);
size_t ngspice__gmin_step__pack
                     (const Ngspice__GminStep   *message,
                      uint8_t             *out);
size_t ngspice__gmin_step__pack_to_buffer
                     (const Ngspice__GminStep   *message,
                      ProtobufCBuffer     *buffer);
Ngspice__GminStep *
       ngspice__gmin_step__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ngspice__gmin_step__free_unpacked
                     (Ngspice__GminStep *message,
                      ProtobufCAllocator *allocator);
/* Ngspice__SourceStep methods */
void   ngspice__source_step__init
                     (Ngspice__SourceStep         *message);
size_t ngspice__source_step__get_packed_size
                     (const Ngspice__SourceStep   *message);
size_t ngspice__source_step__pack
                     (const Ngspice__SourceStep   *message,
                      uint8_t             *out);
size_t ngspice__source_step__pack_to_buffer
                     (const Ngspice__SourceStep   *message,
                      ProtobufCBuffer     *buffer);
Ngspice__SourceStep *
       ngspice__source_step__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ngspice__source_step__free_unpacked
                     (Ngspice__SourceStep *message,
                      ProtobufCAllocator *allocator);
/* Ngspice__DeviceLoadValuesEntry methods */
void   ngspice__device_load_values_entry__init
                     (Ngspice__DeviceLoadValuesEntry         *message);
size_t ngspice__device_load_values_entry__get_packed_size
                     (const Ngspice__DeviceLoadValuesEntry   *message);
size_t ngspice__device_load_values_entry__pack
                     (const Ngspice__DeviceLoadValuesEntry   *message,
                      uint8_t             *out);
size_t ngspice__device_load_values_entry__pack_to_buffer
                     (const Ngspice__DeviceLoadValuesEntry   *message,
                      ProtobufCBuffer     *buffer);
Ngspice__DeviceLoadValuesEntry *
       ngspice__device_load_values_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ngspice__device_load_values_entry__free_unpacked
                     (Ngspice__DeviceLoadValuesEntry *message,
                      ProtobufCAllocator *allocator);
/* Ngspice__DeviceLoad methods */
void   ngspice__device_load__init
                     (Ngspice__DeviceLoad         *message);
size_t ngspice__device_load__get_packed_size
                     (const Ngspice__DeviceLoad   *message);
size_t ngspice__device_load__pack
                     (const Ngspice__DeviceLoad   *message,
                      uint8_t             *out);
size_t ngspice__device_load__pack_to_buffer
                     (const Ngspice__DeviceLoad   *message,
                      ProtobufCBuffer     *buffer);
Ngspice__DeviceLoad *
       ngspice__device_load__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ngspice__device_load__free_unpacked
                     (Ngspice__DeviceLoad *message,
                      ProtobufCAllocator *allocator);
/* Ngspice__MatrixCondition methods */
void   ngspice__matrix_condition__init
                     (Ngspice__MatrixCondition         *message);
size_t ngspice__matrix_condition__get_packed_size
                     (const Ngspice__MatrixCondition   *message);
size_t ngspice__matrix_condition__pack
                     (const Ngspice__MatrixCondition   *message,
                      uint8_t             *out);
size_t ngspice__matrix_condition__pack_to_buffer
                     (const Ngspice__MatrixCondition   *message,
                      ProtobufCBuffer     *buffer);
Ngspice__MatrixCondition *
       ngspice__matrix_condition__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ngspice__matrix_condition__free_unpacked
                     (Ngspice__MatrixCondition *message,
                      ProtobufCAllocator *allocator);
/* Ngspice__DiagEvent methods */
void   ngspice__diag_event__init
                     (Ngspice__DiagEvent         *message);
size_t ngspice__diag_event__get_packed_size
                     (const Ngspice__DiagEvent   *message);
size_t ngspice__diag_event__pack
                     (const Ngspice__DiagEvent   *message,
                      uint8_t             *out);
size_t ngspice__diag_event__pack_to_buffer
                     (const Ngspice__DiagEvent   *message,
                      ProtobufCBuffer     *buffer);
Ngspice__DiagEvent *
       ngspice__diag_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ngspice__diag_event__free_unpacked
                     (Ngspice__DiagEvent *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Ngspice__SimRequest__OptionsEntry_Closure)
                 (const Ngspice__SimRequest__OptionsEntry *message,
                  void *closure_data);
typedef void (*Ngspice__SimRequest_Closure)
                 (const Ngspice__SimRequest *message,
                  void *closure_data);
typedef void (*Ngspice__BatchSimRequest_Closure)
                 (const Ngspice__BatchSimRequest *message,
                  void *closure_data);
typedef void (*Ngspice__VectorData_Closure)
                 (const Ngspice__VectorData *message,
                  void *closure_data);
typedef void (*Ngspice__SimResult__NodeVoltagesEntry_Closure)
                 (const Ngspice__SimResult__NodeVoltagesEntry *message,
                  void *closure_data);
typedef void (*Ngspice__SimResult__BranchCurrentsEntry_Closure)
                 (const Ngspice__SimResult__BranchCurrentsEntry *message,
                  void *closure_data);
typedef void (*Ngspice__SimResult_Closure)
                 (const Ngspice__SimResult *message,
                  void *closure_data);
typedef void (*Ngspice__BatchSimResult_Closure)
                 (const Ngspice__BatchSimResult *message,
                  void *closure_data);
typedef void (*Ngspice__ServerStats_Closure)
                 (const Ngspice__ServerStats *message,
                  void *closure_data);
typedef void (*Ngspice__NRIteration_Closure)
                 (const Ngspice__NRIteration *message,
                  void *closure_data);
typedef void (*Ngspice__LimiterActivation_Closure)
                 (const Ngspice__LimiterActivation *message,
                  void *closure_data);
typedef void (*Ngspice__GminStep_Closure)
                 (const Ngspice__GminStep *message,
                  void *closure_data);
typedef void (*Ngspice__SourceStep_Closure)
                 (const Ngspice__SourceStep *message,
                  void *closure_data);
typedef void (*Ngspice__DeviceLoadValuesEntry_Closure)
                 (const Ngspice__DeviceLoadValuesEntry *message,
                  void *closure_data);
typedef void (*Ngspice__DeviceLoad_Closure)
                 (const Ngspice__DeviceLoad *message,
                  void *closure_data);
typedef void (*Ngspice__MatrixCondition_Closure)
                 (const Ngspice__MatrixCondition *message,
                  void *closure_data);
typedef void (*Ngspice__DiagEvent_Closure)
                 (const Ngspice__DiagEvent *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ngspice__sim_request__descriptor;
extern const ProtobufCMessageDescriptor ngspice__sim_request__options_entry__descriptor;
extern const ProtobufCMessageDescriptor ngspice__batch_sim_request__descriptor;
extern const ProtobufCMessageDescriptor ngspice__vector_data__descriptor;
extern const ProtobufCMessageDescriptor ngspice__sim_result__descriptor;
extern const ProtobufCMessageDescriptor ngspice__sim_result__node_voltages_entry__descriptor;
extern const ProtobufCMessageDescriptor ngspice__sim_result__branch_currents_entry__descriptor;
extern const ProtobufCEnumDescriptor    ngspice__sim_result__error_code__descriptor;
extern const ProtobufCMessageDescriptor ngspice__batch_sim_result__descriptor;
extern const ProtobufCMessageDescriptor ngspice__server_stats__descriptor;
extern const ProtobufCMessageDescriptor ngspice__nriteration__descriptor;
extern const ProtobufCMessageDescriptor ngspice__limiter_activation__descriptor;
extern const ProtobufCMessageDescriptor ngspice__gmin_step__descriptor;
extern const ProtobufCMessageDescriptor ngspice__source_step__descriptor;
extern const ProtobufCMessageDescriptor ngspice__device_load_values_entry__descriptor;
extern const ProtobufCMessageDescriptor ngspice__device_load__descriptor;
extern const ProtobufCMessageDescriptor ngspice__matrix_condition__descriptor;
extern const ProtobufCMessageDescriptor ngspice__diag_event__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ngspice_5fsim_2eproto__INCLUDED */
