/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ngspice_sim.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ngspice_sim.pb-c.h"
void   ngspice__sim_request__options_entry__init
                     (Ngspice__SimRequest__OptionsEntry         *message)
{
  static const Ngspice__SimRequest__OptionsEntry init_value = NGSPICE__SIM_REQUEST__OPTIONS_ENTRY__INIT;
  *message = init_value;
}
void   ngspice__sim_request__init
                     (Ngspice__SimRequest         *message)
{
  static const Ngspice__SimRequest init_value = NGSPICE__SIM_REQUEST__INIT;
  *message = init_value;
}
size_t ngspice__sim_request__get_packed_size
                     (const Ngspice__SimRequest *message)
{
  assert(message->base.descriptor == &ngspice__sim_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ngspice__sim_request__pack
                     (const Ngspice__SimRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ngspice__sim_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ngspice__sim_request__pack_to_buffer
                     (const Ngspice__SimRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ngspice__sim_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ngspice__SimRequest *
       ngspice__sim_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ngspice__SimRequest *)
     protobuf_c_message_unpack (&ngspice__sim_request__descriptor,
                                allocator, len, data);
}
void   ngspice__sim_request__free_unpacked
                     (Ngspice__SimRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ngspice__sim_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ngspice__batch_sim_request__init
                     (Ngspice__BatchSimRequest         *message)
{
  static const Ngspice__BatchSimRequest init_value = NGSPICE__BATCH_SIM_REQUEST__INIT;
  *message = init_value;
}
size_t ngspice__batch_sim_request__get_packed_size
                     (const Ngspice__BatchSimRequest *message)
{
  assert(message->base.descriptor == &ngspice__batch_sim_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ngspice__batch_sim_request__pack
                     (const Ngspice__BatchSimRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ngspice__batch_sim_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ngspice__batch_sim_request__pack_to_buffer
                     (const Ngspice__BatchSimRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ngspice__batch_sim_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ngspice__BatchSimRequest *
       ngspice__batch_sim_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ngspice__BatchSimRequest *)
     protobuf_c_message_unpack (&ngspice__batch_sim_request__descriptor,
                                allocator, len, data);
}
void   ngspice__batch_sim_request__free_unpacked
                     (Ngspice__BatchSimRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ngspice__batch_sim_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ngspice__vector_data__init
                     (Ngspice__VectorData         *message)
{
  static const Ngspice__VectorData init_value = NGSPICE__VECTOR_DATA__INIT;
  *message = init_value;
}
size_t ngspice__vector_data__get_packed_size
                     (const Ngspice__VectorData *message)
{
  assert(message->base.descriptor == &ngspice__vector_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ngspice__vector_data__pack
                     (const Ngspice__VectorData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ngspice__vector_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ngspice__vector_data__pack_to_buffer
                     (const Ngspice__VectorData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ngspice__vector_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ngspice__VectorData *
       ngspice__vector_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ngspice__VectorData *)
     protobuf_c_message_unpack (&ngspice__vector_data__descriptor,
                                allocator, len, data);
}
void   ngspice__vector_data__free_unpacked
                     (Ngspice__VectorData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ngspice__vector_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ngspice__sim_result__node_voltages_entry__init
                     (Ngspice__SimResult__NodeVoltagesEntry         *message)
{
  static const Ngspice__SimResult__NodeVoltagesEntry init_value = NGSPICE__SIM_RESULT__NODE_VOLTAGES_ENTRY__INIT;
  *message = init_value;
}
void   ngspice__sim_result__branch_currents_entry__init
                     (Ngspice__SimResult__BranchCurrentsEntry         *message)
{
  static const Ngspice__SimResult__BranchCurrentsEntry init_value = NGSPICE__SIM_RESULT__BRANCH_CURRENTS_ENTRY__INIT;
  *message = init_value;
}
void   ngspice__sim_result__init
                     (Ngspice__SimResult         *message)
{
  static const Ngspice__SimResult init_value = NGSPICE__SIM_RESULT__INIT;
  *message = init_value;
}
size_t ngspice__sim_result__get_packed_size
                     (const Ngspice__SimResult *message)
{
  assert(message->base.descriptor == &ngspice__sim_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ngspice__sim_result__pack
                     (const Ngspice__SimResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ngspice__sim_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ngspice__sim_result__pack_to_buffer
                     (const Ngspice__SimResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ngspice__sim_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ngspice__SimResult *
       ngspice__sim_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ngspice__SimResult *)
     protobuf_c_message_unpack (&ngspice__sim_result__descriptor,
                                allocator, len, data);
}
void   ngspice__sim_result__free_unpacked
                     (Ngspice__SimResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ngspice__sim_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ngspice__batch_sim_result__init
                     (Ngspice__BatchSimResult         *message)
{
  static const Ngspice__BatchSimResult init_value = NGSPICE__BATCH_SIM_RESULT__INIT;
  *message = init_value;
}
size_t ngspice__batch_sim_result__get_packed_size
                     (const Ngspice__BatchSimResult *message)
{
  assert(message->base.descriptor == &ngspice__batch_sim_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ngspice__batch_sim_result__pack
                     (const Ngspice__BatchSimResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ngspice__batch_sim_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ngspice__batch_sim_result__pack_to_buffer
                     (const Ngspice__BatchSimResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ngspice__batch_sim_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ngspice__BatchSimResult *
       ngspice__batch_sim_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ngspice__BatchSimResult *)
     protobuf_c_message_unpack (&ngspice__batch_sim_result__descriptor,
                                allocator, len, data);
}
void   ngspice__batch_sim_result__free_unpacked
                     (Ngspice__BatchSimResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ngspice__batch_sim_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ngspice__server_stats__init
                     (Ngspice__ServerStats         *message)
{
  static const Ngspice__ServerStats init_value = NGSPICE__SERVER_STATS__INIT;
  *message = init_value;
}
size_t ngspice__server_stats__get_packed_size
                     (const Ngspice__ServerStats *message)
{
  assert(message->base.descriptor == &ngspice__server_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ngspice__server_stats__pack
                     (const Ngspice__ServerStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ngspice__server_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ngspice__server_stats__pack_to_buffer
                     (const Ngspice__ServerStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ngspice__server_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ngspice__ServerStats *
       ngspice__server_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ngspice__ServerStats *)
     protobuf_c_message_unpack (&ngspice__server_stats__descriptor,
                                allocator, len, data);
}
void   ngspice__server_stats__free_unpacked
                     (Ngspice__ServerStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ngspice__server_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ngspice__nriteration__init
                     (Ngspice__NRIteration         *message)
{
  static const Ngspice__NRIteration init_value = NGSPICE__NRITERATION__INIT;
  *message = init_value;
}
size_t ngspice__nriteration__get_packed_size
                     (const Ngspice__NRIteration *message)
{
  assert(message->base.descriptor == &ngspice__nriteration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ngspice__nriteration__pack
                     (const Ngspice__NRIteration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ngspice__nriteration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ngspice__nriteration__pack_to_buffer
                     (const Ngspice__NRIteration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ngspice__nriteration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ngspice__NRIteration *
       ngspice__nriteration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ngspice__NRIteration *)
     protobuf_c_message_unpack (&ngspice__nriteration__descriptor,
                                allocator, len, data);
}
void   ngspice__nriteration__free_unpacked
                     (Ngspice__NRIteration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ngspice__nriteration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ngspice__limiter_activation__init
                     (Ngspice__LimiterActivation         *message)
{
  static const Ngspice__LimiterActivation init_value = NGSPICE__LIMITER_ACTIVATION__INIT;
  *message = init_value;
}
size_t ngspice__limiter_activation__get_packed_size
                     (const Ngspice__LimiterActivation *message)
{
  assert(message->base.descriptor == &ngspice__limiter_activation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ngspice__limiter_activation__pack
                     (const Ngspice__LimiterActivation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ngspice__limiter_activation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ngspice__limiter_activation__pack_to_buffer
                     (const Ngspice__LimiterActivation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ngspice__limiter_activation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ngspice__LimiterActivation *
       ngspice__limiter_activation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ngspice__LimiterActivation *)
     protobuf_c_message_unpack (&ngspice__limiter_activation__descriptor,
                                allocator, len, data);
}
void   ngspice__limiter_activation__free_unpacked
                     (Ngspice__LimiterActivation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ngspice__limiter_activation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ngspice__gmin_step__init
                     (Ngspice__GminStep         *message)
{
  static const Ngspice__GminStep init_value = NGSPICE__GMIN_STEP__INIT;
  *message = init_value;
}
size_t ngspice__gmin_step__get_packed_size
                     (const Ngspice__GminStep *message)
{
  assert(message->base.descriptor == &ngspice__gmin_step__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ngspice__gmin_step__pack
                     (const Ngspice__GminStep *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ngspice__gmin_step__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ngspice__gmin_step__pack_to_buffer
                     (const Ngspice__GminStep *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ngspice__gmin_step__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ngspice__GminStep *
       ngspice__gmin_step__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ngspice__GminStep *)
     protobuf_c_message_unpack (&ngspice__gmin_step__descriptor,
                                allocator, len, data);
}
void   ngspice__gmin_step__free_unpacked
                     (Ngspice__GminStep *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ngspice__gmin_step__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ngspice__source_step__init
                     (Ngspice__SourceStep         *message)
{
  static const Ngspice__SourceStep init_value = NGSPICE__SOURCE_STEP__INIT;
  *message = init_value;
}
size_t ngspice__source_step__get_packed_size
                     (const Ngspice__SourceStep *message)
{
  assert(message->base.descriptor == &ngspice__source_step__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ngspice__source_step__pack
                     (const Ngspice__SourceStep *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ngspice__source_step__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ngspice__source_step__pack_to_buffer
                     (const Ngspice__SourceStep *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ngspice__source_step__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ngspice__SourceStep *
       ngspice__source_step__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ngspice__SourceStep *)
     protobuf_c_message_unpack (&ngspice__source_step__descriptor,
                                allocator, len, data);
}
void   ngspice__source_step__free_unpacked
                     (Ngspice__SourceStep *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ngspice__source_step__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ngspice__device_load_values_entry__init
                     (Ngspice__DeviceLoadValuesEntry         *message)
{
  static const Ngspice__DeviceLoadValuesEntry init_value = NGSPICE__DEVICE_LOAD_VALUES_ENTRY__INIT;
  *message = init_value;
}
size_t ngspice__device_load_values_entry__get_packed_size
                     (const Ngspice__DeviceLoadValuesEntry *message)
{
  assert(message->base.descriptor == &ngspice__device_load_values_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ngspice__device_load_values_entry__pack
                     (const Ngspice__DeviceLoadValuesEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ngspice__device_load_values_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ngspice__device_load_values_entry__pack_to_buffer
                     (const Ngspice__DeviceLoadValuesEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ngspice__device_load_values_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ngspice__DeviceLoadValuesEntry *
       ngspice__device_load_values_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ngspice__DeviceLoadValuesEntry *)
     protobuf_c_message_unpack (&ngspice__device_load_values_entry__descriptor,
                                allocator, len, data);
}
void   ngspice__device_load_values_entry__free_unpacked
                     (Ngspice__DeviceLoadValuesEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ngspice__device_load_values_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ngspice__device_load__init
                     (Ngspice__DeviceLoad         *message)
{
  static const Ngspice__DeviceLoad init_value = NGSPICE__DEVICE_LOAD__INIT;
  *message = init_value;
}
size_t ngspice__device_load__get_packed_size
                     (const Ngspice__DeviceLoad *message)
{
  assert(message->base.descriptor == &ngspice__device_load__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ngspice__device_load__pack
                     (const Ngspice__DeviceLoad *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ngspice__device_load__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ngspice__device_load__pack_to_buffer
                     (const Ngspice__DeviceLoad *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ngspice__device_load__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ngspice__DeviceLoad *
       ngspice__device_load__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ngspice__DeviceLoad *)
     protobuf_c_message_unpack (&ngspice__device_load__descriptor,
                                allocator, len, data);
}
void   ngspice__device_load__free_unpacked
                     (Ngspice__DeviceLoad *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ngspice__device_load__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ngspice__matrix_condition__init
                     (Ngspice__MatrixCondition         *message)
{
  static const Ngspice__MatrixCondition init_value = NGSPICE__MATRIX_CONDITION__INIT;
  *message = init_value;
}
size_t ngspice__matrix_condition__get_packed_size
                     (const Ngspice__MatrixCondition *message)
{
  assert(message->base.descriptor == &ngspice__matrix_condition__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ngspice__matrix_condition__pack
                     (const Ngspice__MatrixCondition *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ngspice__matrix_condition__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ngspice__matrix_condition__pack_to_buffer
                     (const Ngspice__MatrixCondition *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ngspice__matrix_condition__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ngspice__MatrixCondition *
       ngspice__matrix_condition__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ngspice__MatrixCondition *)
     protobuf_c_message_unpack (&ngspice__matrix_condition__descriptor,
                                allocator, len, data);
}
void   ngspice__matrix_condition__free_unpacked
                     (Ngspice__MatrixCondition *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ngspice__matrix_condition__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ngspice__diag_event__init
                     (Ngspice__DiagEvent         *message)
{
  static const Ngspice__DiagEvent init_value = NGSPICE__DIAG_EVENT__INIT;
  *message = init_value;
}
size_t ngspice__diag_event__get_packed_size
                     (const Ngspice__DiagEvent *message)
{
  assert(message->base.descriptor == &ngspice__diag_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ngspice__diag_event__pack
                     (const Ngspice__DiagEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ngspice__diag_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ngspice__diag_event__pack_to_buffer
                     (const Ngspice__DiagEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ngspice__diag_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ngspice__DiagEvent *
       ngspice__diag_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ngspice__DiagEvent *)
     protobuf_c_message_unpack (&ngspice__diag_event__descriptor,
                                allocator, len, data);
}
void   ngspice__diag_event__free_unpacked
                     (Ngspice__DiagEvent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ngspice__diag_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ngspice__sim_request__options_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SimRequest__OptionsEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SimRequest__OptionsEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ngspice__sim_request__options_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange ngspice__sim_request__options_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ngspice__sim_request__options_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ngspice.SimRequest.OptionsEntry",
  "OptionsEntry",
  "Ngspice__SimRequest__OptionsEntry",
  "ngspice",
  sizeof(Ngspice__SimRequest__OptionsEntry),
  2,
  ngspice__sim_request__options_entry__field_descriptors,
  ngspice__sim_request__options_entry__field_indices_by_name,
  1,  ngspice__sim_request__options_entry__number_ranges,
  (ProtobufCMessageInit) ngspice__sim_request__options_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ngspice__sim_request__field_descriptors[5] =
{
  {
    "netlist",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SimRequest, netlist),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "analysis",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SimRequest, analysis),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "options",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ngspice__SimRequest, n_options),
    offsetof(Ngspice__SimRequest, options),
    &ngspice__sim_request__options_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream_diagnostics",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SimRequest, stream_diagnostics),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_id",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SimRequest, request_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ngspice__sim_request__field_indices_by_name[] = {
  1,   /* field[1] = analysis */
  0,   /* field[0] = netlist */
  2,   /* field[2] = options */
  4,   /* field[4] = request_id */
  3,   /* field[3] = stream_diagnostics */
};
static const ProtobufCIntRange ngspice__sim_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ngspice__sim_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ngspice.SimRequest",
  "SimRequest",
  "Ngspice__SimRequest",
  "ngspice",
  sizeof(Ngspice__SimRequest),
  5,
  ngspice__sim_request__field_descriptors,
  ngspice__sim_request__field_indices_by_name,
  1,  ngspice__sim_request__number_ranges,
  (ProtobufCMessageInit) ngspice__sim_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ngspice__batch_sim_request__field_descriptors[1] =
{
  {
    "requests",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ngspice__BatchSimRequest, n_requests),
    offsetof(Ngspice__BatchSimRequest, requests),
    &ngspice__sim_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ngspice__batch_sim_request__field_indices_by_name[] = {
  0,   /* field[0] = requests */
};
static const ProtobufCIntRange ngspice__batch_sim_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ngspice__batch_sim_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ngspice.BatchSimRequest",
  "BatchSimRequest",
  "Ngspice__BatchSimRequest",
  "ngspice",
  sizeof(Ngspice__BatchSimRequest),
  1,
  ngspice__batch_sim_request__field_descriptors,
  ngspice__batch_sim_request__field_indices_by_name,
  1,  ngspice__batch_sim_request__number_ranges,
  (ProtobufCMessageInit) ngspice__batch_sim_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ngspice__vector_data__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ngspice__VectorData, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "real_values",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Ngspice__VectorData, n_real_values),
    offsetof(Ngspice__VectorData, real_values),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imag_values",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Ngspice__VectorData, n_imag_values),
    offsetof(Ngspice__VectorData, imag_values),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ngspice__vector_data__field_indices_by_name[] = {
  2,   /* field[2] = imag_values */
  0,   /* field[0] = name */
  1,   /* field[1] = real_values */
};
static const ProtobufCIntRange ngspice__vector_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ngspice__vector_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ngspice.VectorData",
  "VectorData",
  "Ngspice__VectorData",
  "ngspice",
  sizeof(Ngspice__VectorData),
  3,
  ngspice__vector_data__field_descriptors,
  ngspice__vector_data__field_indices_by_name,
  1,  ngspice__vector_data__number_ranges,
  (ProtobufCMessageInit) ngspice__vector_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ngspice__sim_result__node_voltages_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SimResult__NodeVoltagesEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SimResult__NodeVoltagesEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ngspice__sim_result__node_voltages_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange ngspice__sim_result__node_voltages_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ngspice__sim_result__node_voltages_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ngspice.SimResult.NodeVoltagesEntry",
  "NodeVoltagesEntry",
  "Ngspice__SimResult__NodeVoltagesEntry",
  "ngspice",
  sizeof(Ngspice__SimResult__NodeVoltagesEntry),
  2,
  ngspice__sim_result__node_voltages_entry__field_descriptors,
  ngspice__sim_result__node_voltages_entry__field_indices_by_name,
  1,  ngspice__sim_result__node_voltages_entry__number_ranges,
  (ProtobufCMessageInit) ngspice__sim_result__node_voltages_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ngspice__sim_result__branch_currents_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SimResult__BranchCurrentsEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SimResult__BranchCurrentsEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ngspice__sim_result__branch_currents_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange ngspice__sim_result__branch_currents_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ngspice__sim_result__branch_currents_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ngspice.SimResult.BranchCurrentsEntry",
  "BranchCurrentsEntry",
  "Ngspice__SimResult__BranchCurrentsEntry",
  "ngspice",
  sizeof(Ngspice__SimResult__BranchCurrentsEntry),
  2,
  ngspice__sim_result__branch_currents_entry__field_descriptors,
  ngspice__sim_result__branch_currents_entry__field_indices_by_name,
  1,  ngspice__sim_result__branch_currents_entry__number_ranges,
  (ProtobufCMessageInit) ngspice__sim_result__branch_currents_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ngspice__sim_result__error_code__enum_values_by_number[7] =
{
  { "OK", "NGSPICE__SIM_RESULT__ERROR_CODE__OK", 0 },
  { "PARSE_ERROR", "NGSPICE__SIM_RESULT__ERROR_CODE__PARSE_ERROR", 1 },
  { "CONVERGENCE_FAILURE", "NGSPICE__SIM_RESULT__ERROR_CODE__CONVERGENCE_FAILURE", 2 },
  { "SINGULAR_MATRIX", "NGSPICE__SIM_RESULT__ERROR_CODE__SINGULAR_MATRIX", 3 },
  { "INTERNAL_ERROR", "NGSPICE__SIM_RESULT__ERROR_CODE__INTERNAL_ERROR", 4 },
  { "TIMEOUT", "NGSPICE__SIM_RESULT__ERROR_CODE__TIMEOUT", 5 },
  { "SERVER_BUSY", "NGSPICE__SIM_RESULT__ERROR_CODE__SERVER_BUSY", 6 },
};
static const ProtobufCIntRange ngspice__sim_result__error_code__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex ngspice__sim_result__error_code__enum_values_by_name[7] =
{
  { "CONVERGENCE_FAILURE", 2 },
  { "INTERNAL_ERROR", 4 },
  { "OK", 0 },
  { "PARSE_ERROR", 1 },
  { "SERVER_BUSY", 6 },
  { "SINGULAR_MATRIX", 3 },
  { "TIMEOUT", 5 },
};
const ProtobufCEnumDescriptor ngspice__sim_result__error_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ngspice.SimResult.ErrorCode",
  "ErrorCode",
  "Ngspice__SimResult__ErrorCode",
  "ngspice",
  7,
  ngspice__sim_result__error_code__enum_values_by_number,
  7,
  ngspice__sim_result__error_code__enum_values_by_name,
  1,
  ngspice__sim_result__error_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor ngspice__sim_result__field_descriptors[11] =
{
  {
    "request_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SimResult, request_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "converged",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SimResult, converged),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iterations",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SimResult, iterations),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node_voltages",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ngspice__SimResult, n_node_voltages),
    offsetof(Ngspice__SimResult, node_voltages),
    &ngspice__sim_result__node_voltages_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "branch_currents",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ngspice__SimResult, n_branch_currents),
    offsetof(Ngspice__SimResult, branch_currents),
    &ngspice__sim_result__branch_currents_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warnings",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Ngspice__SimResult, n_warnings),
    offsetof(Ngspice__SimResult, warnings),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wall_time_ms",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SimResult, wall_time_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SimResult, error),
    &ngspice__sim_result__error_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vectors",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ngspice__SimResult, n_vectors),
    offsetof(Ngspice__SimResult, vectors),
    &ngspice__vector_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "analysis_type",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SimResult, analysis_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_points",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SimResult, num_points),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ngspice__sim_result__field_indices_by_name[] = {
  9,   /* field[9] = analysis_type */
  4,   /* field[4] = branch_currents */
  1,   /* field[1] = converged */
  7,   /* field[7] = error */
  2,   /* field[2] = iterations */
  3,   /* field[3] = node_voltages */
  10,   /* field[10] = num_points */
  0,   /* field[0] = request_id */
  8,   /* field[8] = vectors */
  6,   /* field[6] = wall_time_ms */
  5,   /* field[5] = warnings */
};
static const ProtobufCIntRange ngspice__sim_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor ngspice__sim_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ngspice.SimResult",
  "SimResult",
  "Ngspice__SimResult",
  "ngspice",
  sizeof(Ngspice__SimResult),
  11,
  ngspice__sim_result__field_descriptors,
  ngspice__sim_result__field_indices_by_name,
  1,  ngspice__sim_result__number_ranges,
  (ProtobufCMessageInit) ngspice__sim_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ngspice__batch_sim_result__field_descriptors[2] =
{
  {
    "results",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ngspice__BatchSimResult, n_results),
    offsetof(Ngspice__BatchSimResult, results),
    &ngspice__sim_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_wall_time_ms",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__BatchSimResult, total_wall_time_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ngspice__batch_sim_result__field_indices_by_name[] = {
  0,   /* field[0] = results */
  1,   /* field[1] = total_wall_time_ms */
};
static const ProtobufCIntRange ngspice__batch_sim_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ngspice__batch_sim_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ngspice.BatchSimResult",
  "BatchSimResult",
  "Ngspice__BatchSimResult",
  "ngspice",
  sizeof(Ngspice__BatchSimResult),
  2,
  ngspice__batch_sim_result__field_descriptors,
  ngspice__batch_sim_result__field_indices_by_name,
  1,  ngspice__batch_sim_result__number_ranges,
  (ProtobufCMessageInit) ngspice__batch_sim_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ngspice__server_stats__field_descriptors[8] =
{
  {
    "pool_size",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ngspice__ServerStats, pool_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "admit_queued",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ngspice__ServerStats, admit_queued),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "admit_cap",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ngspice__ServerStats, admit_cap),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "workers_busy",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ngspice__ServerStats, workers_busy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "requests_completed",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Ngspice__ServerStats, requests_completed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_busy_replies",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Ngspice__ServerStats, server_busy_replies),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "worker_restarts",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Ngspice__ServerStats, worker_restarts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_timeouts",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Ngspice__ServerStats, request_timeouts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ngspice__server_stats__field_indices_by_name[] = {
  2,   /* field[2] = admit_cap */
  1,   /* field[1] = admit_queued */
  0,   /* field[0] = pool_size */
  7,   /* field[7] = request_timeouts */
  4,   /* field[4] = requests_completed */
  5,   /* field[5] = server_busy_replies */
  6,   /* field[6] = worker_restarts */
  3,   /* field[3] = workers_busy */
};
static const ProtobufCIntRange ngspice__server_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor ngspice__server_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ngspice.ServerStats",
  "ServerStats",
  "Ngspice__ServerStats",
  "ngspice",
  sizeof(Ngspice__ServerStats),
  8,
  ngspice__server_stats__field_descriptors,
  ngspice__server_stats__field_indices_by_name,
  1,  ngspice__server_stats__number_ranges,
  (ProtobufCMessageInit) ngspice__server_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ngspice__nriteration__field_descriptors[6] =
{
  {
    "iter",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ngspice__NRIteration, iter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_dx",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__NRIteration, max_dx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "noncon",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ngspice__NRIteration, noncon),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "converged",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Ngspice__NRIteration, converged),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_rhs",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__NRIteration, max_rhs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "damp",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__NRIteration, damp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ngspice__nriteration__field_indices_by_name[] = {
  3,   /* field[3] = converged */
  5,   /* field[5] = damp */
  0,   /* field[0] = iter */
  1,   /* field[1] = max_dx */
  4,   /* field[4] = max_rhs */
  2,   /* field[2] = noncon */
};
static const ProtobufCIntRange ngspice__nriteration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor ngspice__nriteration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ngspice.NRIteration",
  "NRIteration",
  "Ngspice__NRIteration",
  "ngspice",
  sizeof(Ngspice__NRIteration),
  6,
  ngspice__nriteration__field_descriptors,
  ngspice__nriteration__field_indices_by_name,
  1,  ngspice__nriteration__number_ranges,
  (ProtobufCMessageInit) ngspice__nriteration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ngspice__limiter_activation__field_descriptors[7] =
{
  {
    "function",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ngspice__LimiterActivation, function),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instance",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ngspice__LimiterActivation, instance),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vnew_raw",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__LimiterActivation, vnew_raw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vnew_limited",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__LimiterActivation, vnew_limited),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vold",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__LimiterActivation, vold),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vcrit",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__LimiterActivation, vcrit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vto",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__LimiterActivation, vto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ngspice__limiter_activation__field_indices_by_name[] = {
  0,   /* field[0] = function */
  1,   /* field[1] = instance */
  5,   /* field[5] = vcrit */
  3,   /* field[3] = vnew_limited */
  2,   /* field[2] = vnew_raw */
  4,   /* field[4] = vold */
  6,   /* field[6] = vto */
};
static const ProtobufCIntRange ngspice__limiter_activation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor ngspice__limiter_activation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ngspice.LimiterActivation",
  "LimiterActivation",
  "Ngspice__LimiterActivation",
  "ngspice",
  sizeof(Ngspice__LimiterActivation),
  7,
  ngspice__limiter_activation__field_descriptors,
  ngspice__limiter_activation__field_indices_by_name,
  1,  ngspice__limiter_activation__number_ranges,
  (ProtobufCMessageInit) ngspice__limiter_activation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ngspice__gmin_step__field_descriptors[3] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__GminStep, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "converged",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Ngspice__GminStep, converged),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iterations",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ngspice__GminStep, iterations),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ngspice__gmin_step__field_indices_by_name[] = {
  1,   /* field[1] = converged */
  2,   /* field[2] = iterations */
  0,   /* field[0] = value */
};
static const ProtobufCIntRange ngspice__gmin_step__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ngspice__gmin_step__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ngspice.GminStep",
  "GminStep",
  "Ngspice__GminStep",
  "ngspice",
  sizeof(Ngspice__GminStep),
  3,
  ngspice__gmin_step__field_descriptors,
  ngspice__gmin_step__field_indices_by_name,
  1,  ngspice__gmin_step__number_ranges,
  (ProtobufCMessageInit) ngspice__gmin_step__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ngspice__source_step__field_descriptors[3] =
{
  {
    "factor",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SourceStep, factor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "converged",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SourceStep, converged),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iterations",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ngspice__SourceStep, iterations),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ngspice__source_step__field_indices_by_name[] = {
  1,   /* field[1] = converged */
  0,   /* field[0] = factor */
  2,   /* field[2] = iterations */
};
static const ProtobufCIntRange ngspice__source_step__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ngspice__source_step__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ngspice.SourceStep",
  "SourceStep",
  "Ngspice__SourceStep",
  "ngspice",
  sizeof(Ngspice__SourceStep),
  3,
  ngspice__source_step__field_descriptors,
  ngspice__source_step__field_indices_by_name,
  1,  ngspice__source_step__number_ranges,
  (ProtobufCMessageInit) ngspice__source_step__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ngspice__device_load_values_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ngspice__DeviceLoadValuesEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__DeviceLoadValuesEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ngspice__device_load_values_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange ngspice__device_load_values_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ngspice__device_load_values_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ngspice.DeviceLoadValuesEntry",
  "DeviceLoadValuesEntry",
  "Ngspice__DeviceLoadValuesEntry",
  "ngspice",
  sizeof(Ngspice__DeviceLoadValuesEntry),
  2,
  ngspice__device_load_values_entry__field_descriptors,
  ngspice__device_load_values_entry__field_indices_by_name,
  1,  ngspice__device_load_values_entry__number_ranges,
  (ProtobufCMessageInit) ngspice__device_load_values_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ngspice__device_load__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ngspice__DeviceLoad, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instance",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ngspice__DeviceLoad, instance),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ngspice__DeviceLoad, n_values),
    offsetof(Ngspice__DeviceLoad, values),
    &ngspice__device_load_values_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ngspice__device_load__field_indices_by_name[] = {
  1,   /* field[1] = instance */
  0,   /* field[0] = type */
  2,   /* field[2] = values */
};
static const ProtobufCIntRange ngspice__device_load__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ngspice__device_load__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ngspice.DeviceLoad",
  "DeviceLoad",
  "Ngspice__DeviceLoad",
  "ngspice",
  sizeof(Ngspice__DeviceLoad),
  3,
  ngspice__device_load__field_descriptors,
  ngspice__device_load__field_indices_by_name,
  1,  ngspice__device_load__number_ranges,
  (ProtobufCMessageInit) ngspice__device_load__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ngspice__matrix_condition__field_descriptors[4] =
{
  {
    "size",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ngspice__MatrixCondition, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "min_pivot",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__MatrixCondition, min_pivot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_pivot",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__MatrixCondition, max_pivot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "condition_ratio",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Ngspice__MatrixCondition, condition_ratio),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ngspice__matrix_condition__field_indices_by_name[] = {
  3,   /* field[3] = condition_ratio */
  2,   /* field[2] = max_pivot */
  1,   /* field[1] = min_pivot */
  0,   /* field[0] = size */
};
static const ProtobufCIntRange ngspice__matrix_condition__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ngspice__matrix_condition__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ngspice.MatrixCondition",
  "MatrixCondition",
  "Ngspice__MatrixCondition",
  "ngspice",
  sizeof(Ngspice__MatrixCondition),
  4,
  ngspice__matrix_condition__field_descriptors,
  ngspice__matrix_condition__field_indices_by_name,
  1,  ngspice__matrix_condition__number_ranges,
  (ProtobufCMessageInit) ngspice__matrix_condition__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ngspice__diag_event__field_descriptors[8] =
{
  {
    "request_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ngspice__DiagEvent, request_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp_us",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Ngspice__DiagEvent, timestamp_us),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nr_iter",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ngspice__DiagEvent, event_case),
    offsetof(Ngspice__DiagEvent, nr_iter),
    &ngspice__nriteration__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "limiter",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ngspice__DiagEvent, event_case),
    offsetof(Ngspice__DiagEvent, limiter),
    &ngspice__limiter_activation__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gmin",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ngspice__DiagEvent, event_case),
    offsetof(Ngspice__DiagEvent, gmin),
    &ngspice__gmin_step__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_step",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ngspice__DiagEvent, event_case),
    offsetof(Ngspice__DiagEvent, src_step),
    &ngspice__source_step__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ngspice__DiagEvent, event_case),
    offsetof(Ngspice__DiagEvent, device),
    &ngspice__device_load__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "matrix",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ngspice__DiagEvent, event_case),
    offsetof(Ngspice__DiagEvent, matrix),
    &ngspice__matrix_condition__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ngspice__diag_event__field_indices_by_name[] = {
  6,   /* field[6] = device */
  4,   /* field[4] = gmin */
  3,   /* field[3] = limiter */
  7,   /* field[7] = matrix */
  2,   /* field[2] = nr_iter */
  0,   /* field[0] = request_id */
  5,   /* field[5] = src_step */
  1,   /* field[1] = timestamp_us */
};
static const ProtobufCIntRange ngspice__diag_event__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 2 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor ngspice__diag_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ngspice.DiagEvent",
  "DiagEvent",
  "Ngspice__DiagEvent",
  "ngspice",
  sizeof(Ngspice__DiagEvent),
  8,
  ngspice__diag_event__field_descriptors,
  ngspice__diag_event__field_indices_by_name,
  2,  ngspice__diag_event__number_ranges,
  (ProtobufCMessageInit) ngspice__diag_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
